name = "ket-quiz"
compatibility_date = "2024-01-01"
pages_build_output_dir = "frontend"

[[d1_databases]]
binding = "DB"
database_name = "ket-quiz-db"
database_id = "bd1d61d3-9637-477e-9f22-3039f7119b7e"
